"""
JIZO - Part 3 seed script (owner: Aayush, P3).

Fills a fresh database with the registry policies and a few representative
drill runs, so the dashboard has something to show and `/health` reports
real numbers without anyone running a drill first.

Run it with:

    .\\.venv\\Scripts\\python.exe -m backend.seed

## Why this works before P2 exists

The demo runs below are generated by **calling P1's scorer directly**.
`score_run(spec, events)` is a pure function - data in, data out - so we can
build a realistic `EvidenceEvent` timeline on the evidence bus, grade it,
and persist the result. No proxy, no network, no upstream API.

That matters for the build order: P2 (the protector) has not been written,
but P3 does not depend on it. This is how P3 stays unblocked.

## The numbers are cited, not invented

Doc Sec. 11.4 is the designated source ("Do not invent thresholds; use
defaults in Sec. 11.4"), and `backend/config.py` reads the same values from
`.env`. These are copied from published tuning in `notes/README.md` Sec. 1,
so a judge asking "why 25%?" gets a citation rather than a shrug.

`api_key` values are aligned to Part 2's merged `config.py`, which is the
running source of truth: Aditi's registry uses `weather` and `geocode`, and
`proxy.py` resolves policies through `load_policy(api_key)`. A registry row
keyed `open-meteo` would never be found, so the demo would fail on a missing
policy.

Note this means the build doc's own example log line (Sec. 7.3, which prints
`"api":"open-meteo"`) disagrees with the merged code. P2 landed first and its
180 tests depend on these names, so P3 follows P2. Worth raising so the log
example and the code end up saying the same thing.
"""

from __future__ import annotations

import asyncio

from sqlalchemy import func, select
from sqlalchemy.exc import ProgrammingError
from sqlalchemy.ext.asyncio import AsyncSession

from .db import dispose_engine, get_sessionmaker
from .faults import (
    EvidenceBus,
    k_of_n_drill,
    order_sensitive_drill,
    post_effect_drill,
)
from .models import (
    ApiRegistryRow,
    BreakerTransitionRow,
    FiRunRow,
    RequestLogRow,
)
from .schemas import (
    ApiPolicy,
    BreakerState,
    EvidenceEvent,
    FaultType,
    Phase,
    ScoreResult,
    ServedFrom,
)
from .scoring import score_run
from .secrets import get_config
from .store import policy_to_row, record_transition, save_run


# ---------------------------------------------------------------------------
# 1. api_registry  <- ApiPolicy   (values: Doc Sec. 11.4)
# ---------------------------------------------------------------------------


def _policies() -> tuple[ApiPolicy, ...]:
    """Build the registry from `config.py` so both read one source."""
    cfg = get_config()

    return (
        ApiPolicy(
            # Aligned to P2's config.py registry key: `weather`.
            api_key="weather",
            base_url=cfg.openmeteo_base,
            timeout_s=cfg.upstream_timeout,
            max_attempts=cfg.max_attempts,
            backoff_initial_s=0.075,   # BACKOFF_INIT=75ms [Pasunoori 2025 Sec.6]
            backoff_max_s=1.8,        # BACKOFF_MAX=1.8s  [-52% recovery time]
            jitter_s=0.05,            # JITTER=50ms       [83% stability]
            breaker_window=100,       # WINDOW=100    [Pasunoori 2025 Sec.2]
            breaker_error_threshold=0.25,  # ERROR_PCT=25 [20-30% optimal band]
            breaker_min_volume=20,    # VOLUME_MIN=20     [Pasunoori 2025 Sec.2]
            breaker_sleep_s=10.0,     # SLEEP=10          [beginner doc Sec.6C]
            half_open_probes=10,      # PROBE_RATE '10/5s', 94.7% accuracy
            half_open_window_s=5.0,
            # A forecast read is safe to retry.
            idempotent=True,
            criticality="medium",
        ),
        ApiPolicy(
            # Aligned to P2's config.py registry key: `geocode`.
            api_key="geocode",
            base_url=cfg.nominatim_base,
            timeout_s=cfg.upstream_timeout,
            max_attempts=cfg.max_attempts,
            backoff_initial_s=0.075,
            backoff_max_s=1.8,
            jitter_s=0.05,
            breaker_window=100,
            breaker_error_threshold=0.25,
            breaker_min_volume=20,
            breaker_sleep_s=10.0,
            half_open_probes=10,
            half_open_window_s=5.0,
            idempotent=True,
            # Aligned to P2's config.py, which has geocode at "medium". The
            # previous value here was "low" while the comment claimed it
            # mattered MORE than weather - a comment contradicting its code,
            # and a silent disagreement with the running registry.
            criticality="medium",
            # Sec. 10: Nominatim requires <= 1 rps courtesy.
            courtesy_rps=cfg.nominatim_rps,
        ),
        ApiPolicy(
            # Not one of the two demo upstreams. This stands in for the
            # state-changing write that the post-effect pattern exists to
            # reason about (Sec. 8.1: "Charge/order committed, then drop
            # response -> caller timeout; must not double-dispatch").
            api_key="payment",
            base_url="https://api.internal.example/v1/charge",
            timeout_s=cfg.upstream_timeout,
            # Fewer attempts than a read: retrying a charge is risky, so we
            # give up sooner rather than hammer it.
            max_attempts=2,
            backoff_initial_s=0.075,
            backoff_max_s=1.8,
            jitter_s=0.05,
            breaker_window=100,
            breaker_error_threshold=0.25,
            breaker_min_volume=20,
            breaker_sleep_s=10.0,
            half_open_probes=10,
            half_open_window_s=5.0,
            # The important one: a charge is NOT safe to retry blindly.
            # 51.0% of real operations are state-changing (Tan et al. 2026
            # Table I), which is why this is per-operation and never
            # inferred from the HTTP method.
            idempotent=False,
            criticality="high",
        ),
    )


# ---------------------------------------------------------------------------
# 2. Demo runs - realistic evidence, graded by the real scorer
# ---------------------------------------------------------------------------


def build_k_of_n_run() -> tuple[ScoreResult, list[EvidenceEvent]]:
    """Pattern 3 - the headline demo: only call 3 of 4 breaks.

    Sec. 11.3: "Inject k-of-n: 4x geocode, drop #3 -> only #3 fallback."
    This is the case the dashboard should lead with, because it proves the
    protection is *precise* (only the intended call degrades) rather than
    blunt (everything degrades). Doc Sec. 8.1 guard intuition:
    After(#2 OK), target k=3.

        call 1: SEND -> RECV LIVE                      healthy
        call 2: SEND -> RECV LIVE                      healthy
        call 3: SEND -> RECV (fault http_500, NONE)
                     -> RECV CACHE                     recovered from cache
        call 4: SEND -> RECV LIVE                      healthy

    Expected: TS=PASS - the faulted call still served the customer, and every
    healthy call served live data.
    """
    bus = EvidenceBus()
    trace = "seed-k-of-n"
    api = "geocode"  # Sec. 11.3 uses geocode for the k-of-n demo

    for _ in range(2):
        bus.record(trace, api, Phase.SEND)
        bus.record(trace, api, Phase.RECV, served_from=ServedFrom.LIVE)

    bus.record(trace, api, Phase.SEND)
    bus.record(
        trace, api, Phase.RECV,
        fault=FaultType.HTTP_500, served_from=ServedFrom.NONE, status_code=500,
    )
    bus.record(trace, api, Phase.RECV, served_from=ServedFrom.CACHE)

    bus.record(trace, api, Phase.SEND)
    bus.record(trace, api, Phase.RECV, served_from=ServedFrom.LIVE)

    spec = k_of_n_drill("seed-run-k-of-n", api, k=3, n=4)
    return score_run(spec, bus.events(trace)), bus.events(trace)


def build_post_effect_run() -> tuple[ScoreResult, list[EvidenceEvent]]:
    """Pattern 1 - the answer is lost AFTER the charge committed.

    The dangerous pattern (Sec. 8.1). The upstream did the work, then the
    response vanished, so the caller cannot tell whether it succeeded.
    Correct handling serves the customer from cache and does NOT commit a
    second time.

        call 1: SEND -> POST_EFFECT (effect applied)
                     -> RECV (fault drop_response, NONE)
                     -> RECV CACHE                    customer still served

    Expected: TS=PASS - one effect, customer served, fault landed after the
    commit evidence the guard was waiting for.
    """
    bus = EvidenceBus()
    trace = "seed-post-effect"
    api = "payment"

    bus.record(trace, api, Phase.SEND)
    bus.record(trace, api, Phase.POST_EFFECT, effect_applied=True)
    bus.record(
        trace, api, Phase.RECV,
        fault=FaultType.DROP_RESPONSE, served_from=ServedFrom.NONE,
    )
    bus.record(trace, api, Phase.RECV, served_from=ServedFrom.CACHE)

    spec = post_effect_drill("seed-run-post-effect", api, k=1, n=1)
    return score_run(spec, bus.events(trace)), bus.events(trace)


def build_order_sensitive_run() -> tuple[ScoreResult, list[EvidenceEvent]]:
    """Pattern 2 - a rival answer arrives first; do not trust it.

    Sec. 8.1: "CreateUser OK before RiskCheck FAIL -> caller commits success
    too early; delay FAIL until after OK." Guard intuition:
    After(recv User OK).

        call 1: SEND -> RECV (fault rival_response, NONE)
                     -> RECV MESSAGE                  safe, honest answer

    Expected: TS=PASS - rival not served as live data, no commit on
    unverified data, customer still told something useful.
    """
    bus = EvidenceBus()
    trace = "seed-order-sensitive"
    api = "weather"

    bus.record(trace, api, Phase.SEND)
    bus.record(
        trace, api, Phase.RECV,
        fault=FaultType.RIVAL_RESPONSE, served_from=ServedFrom.NONE,
    )
    # MESSAGE, not LIVE. That difference is the whole pattern: leaking the
    # stale payload as live data is the bug this drill exists to catch.
    bus.record(trace, api, Phase.RECV, served_from=ServedFrom.MESSAGE)

    spec = order_sensitive_drill("seed-run-order-sensitive", api, k=1, n=1)
    return score_run(spec, bus.events(trace)), bus.events(trace)


#: Run builders. Each returns (score, evidence rows) for one representative
#: drill.
RUN_BUILDERS = (
    build_k_of_n_run,
    build_post_effect_run,
    build_order_sensitive_run,
)


# ---------------------------------------------------------------------------
# 3. Entry point
#
# Persistence lives in `backend/store.py`, which is the public API Part 4
# codes against. The seed deliberately no longer owns its own mappers - two
# copies of the same mapping is exactly how the two would drift.
# ---------------------------------------------------------------------------


async def seed(session: AsyncSession, reset: bool = False) -> dict[str, int]:
    """Insert registry policies and demo runs."""
    if reset:
        for model in (RequestLogRow, FiRunRow, BreakerTransitionRow, ApiRegistryRow):
            await session.execute(model.__table__.delete())
        await session.commit()
        print("[seed] cleared existing rows")

    # -- api_registry ----------------------------------------------------
    # One mapping, not two: the insert goes through `store.policy_to_row()`
    # so a new `ApiPolicy` field lands in the seed automatically instead of
    # needing a second edit here.
    policies = _policies()
    for policy in policies:
        if await session.get(ApiRegistryRow, policy.api_key) is None:
            session.add(policy_to_row(policy, owner="team-praann"))
    await session.commit()
    print(f"[seed] {len(policies)} api_registry rows ready")

    # -- fi_runs + request_logs ------------------------------------------
    events_written = 0
    for builder in RUN_BUILDERS:
        result, events = builder()

        # Spec, evidence and verdict in ONE transaction via the public API.
        #
        # PRD Sec. 7.6 / Doc Sec. 7.6 define one `fi_runs` table holding both
        # intent and verdict, and `run_id` is its primary key, so the verdict
        # is written into the row the spec created. `save_run` also repairs an
        # incomplete run, which the old two-commit seed could strand as a
        # permanent `ts IS NULL`.
        existing = await session.get(FiRunRow, result.run_id)
        if existing is not None and existing.ts is not None:
            print(f"[seed] {result.run_id}: already present, skipped")
            continue

        await save_run(session, result.spec, result, events)
        events_written += len(events)
        print(f"[seed] {result.run_id}: {result.explain()}")

    # -- breaker_transitions ---------------------------------------------
    # A CLOSED baseline entry per api, so `/breaker/state` (Sec. 7.7) and the
    # dashboard's "all CLOSED" starting state (Sec. 11.3 step 1) have
    # something to read before Aditi's P2 writes real transitions.
    #
    # Per-api, not global: checking "does ANY transition exist" meant adding
    # a fourth upstream later left it with no baseline row at all.
    have_baseline = set(
        (
            await session.execute(select(BreakerTransitionRow.api_key).distinct())
        ).scalars().all()
    )
    missing = [p for p in policies if p.api_key not in have_baseline]
    if missing:
        for policy in missing:
            await record_transition(
                session,
                api_key=policy.api_key,
                from_state=None,          # first entry: breaker registered
                to_state=BreakerState.CLOSED,
                error_pct=0.0,
                reason="seed baseline: breaker registered CLOSED",
                commit=False,
            )
        await session.commit()
        print(f"[seed] {len(missing)} baseline breaker transitions")

    print(f"[seed] done - {len(policies)} registry rows, "
          f"{len(RUN_BUILDERS)} runs, {events_written} request_logs rows")
    return {
        "registry": len(policies),
        "runs": len(RUN_BUILDERS),
        "logs": events_written,
    }


async def _require_schema(session: AsyncSession) -> None:
    """Fail with a clear message if the migration has not been run.

    We deliberately do NOT call `Base.metadata.create_all` here. Doing so
    produced a schema that (a) lacked every server default the migration
    sets, (b) had no `alembic_version` row, and (c) could then never be
    migrated - `alembic upgrade head` fails with DuplicateTableError because
    the tables already exist. One schema authority, and it is Alembic.
    """
    try:
        await session.execute(select(func.count()).select_from(ApiRegistryRow))
    except ProgrammingError:
        # `from None` on purpose: the chained asyncpg/sqlalchemy traceback
        # says only that api_registry is missing, which the message below
        # already states far more usefully. The chain buried the actionable
        # line under a screen of driver noise.
        raise RuntimeError(
            "database schema is missing - run `alembic upgrade head` first"
        ) from None


async def _main() -> None:
    # Alembic is the single source of truth for the schema:
    #     .\.venv\Scripts\python.exe -m alembic upgrade head
    #     .\.venv\Scripts\python.exe -m backend.seed
    factory = get_sessionmaker()

    async with factory() as session:
        await _require_schema(session)
        stats = await seed(session)

    await dispose_engine()
    print("\nSeed complete:", stats)


if __name__ == "__main__":
    asyncio.run(_main())
